version: "3.2"
services:
  php:
    build: './app/'
    volumes:
      - ./app/samplephpwebsite/:/var/www/htdocs/
  apache:
    build: './apache/'
    depends_on:
      - php
    links: 
      - php
    ports:
      - "8080:80"
    volumes:
      - ./app/samplephpwebsite/:/var/www/htdocs/