version: "3.2"
services:
  php:
    build: './app/'
    volumes:
      - ./app/samplephpwebsite/:/var/www/html/
    networks: 
      - backends
  apache:
    build: './apache/'
    depends_on:
      - php
    links: 
      - php
    ports:
      - "8080:80"
    networks: 
      - backends
    volumes:
      - ./app/samplephpwebsite/:/var/www/html/
networks: 
  backends:
    driver: bridge